version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./usr/src/app"
    depends_on:
      - db
      
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2    

    volumes:
      - ./data/db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env      
    volumes:
    - ./data/pgadmin-data:/var/lib/pgadmin
    ports: 
      - "5050:80"
    depends_on:
    - db
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
   